In [2]:
!ls -halt

total 336280
drwxr-xr-x  21 suyashs  staff   672B Apr 26 21:53 .
-rw-r--r--   1 suyashs  staff    18K Apr 26 21:53 E-Commerce EDA.ipynb
-rw-r--r--   1 suyashs  staff   132K Apr 25 19:31 order_reviews_before.html
-rw-r--r--   1 suyashs  staff   223K Apr 25 19:31 order_payments_before.html
-rw-r--r--   1 suyashs  staff   218K Apr 25 19:31 order_items_before.html
-rw-r--r--   1 suyashs  staff   236K Apr 25 19:30 geolocations_before.html
-rw-r--r--   1 suyashs  staff   120K Apr 25 19:29 sellers_before.html
-rw-r--r--   1 suyashs  staff   129K Apr 25 19:29 customers_before.html
-rw-r--r--   1 suyashs  staff   426K Apr 25 19:29 products_before.html
drwxr-xr-x   3 suyashs  staff    96B Apr 25 18:12 .ipynb_checkpoints
-rw-r--r--@  1 suyashs  staff    42M Apr 25 18:10 brazilian-ecommerce.zip
drwxr-xr-x  13 suyashs  staff   416B Apr 25 18:10 ..
-rwx------@  1 suyashs  staff    58M Nov 29 12:23 olist_geolocation_dataset.csv
-rwx------@  1 suyashs  staff    15M Nov 29 12:23 olist_order_items_dataset.csv
-rwx------@  1 suyashs  staff    17M Nov 29 12:23 olist_orders_dataset.csv
-rwx------@  1 suyashs  staff   8.6M Nov 29 12:23 olist_customers_dataset.csv
-rwx------@  1 suyashs  staff   5.5M Nov 29 12:23 olist_order_payments_dataset.csv
-rwx------@  1 suyashs  staff    14M Nov 29 12:23 olist_order_reviews_dataset.csv
-rwx------@  1 suyashs  staff   2.3M Nov 29 12:23 olist_products_dataset.csv
-rwx------@  1 suyashs  staff   171K Nov 29 12:23 olist_sellers_dataset.csv
-rwx------@  1 suyashs  staff   2.6K Nov 29 12:23 product_category_name_translation.csv

In [3]:
# Give some permissions on the files
!chmod u=rwx *.csv

In [4]:
import numpy as np
import pandas as pd
import pandas_profiling

In [128]:
products           = pd.read_csv("olist_products_dataset.csv")
customers          = pd.read_csv("olist_customers_dataset.csv")
sellers            = pd.read_csv("olist_sellers_dataset.csv")
geolocations       = pd.read_csv("olist_geolocation_dataset.csv")

orders             = pd.read_csv("olist_orders_dataset.csv")
order_items        = pd.read_csv("olist_order_items_dataset.csv")
order_payments     = pd.read_csv("olist_order_payments_dataset.csv")
order_reviews      = pd.read_csv("olist_order_reviews_dataset.csv")

cat_translate      = pd.read_csv("product_category_name_translation.csv")

In [127]:
products.head()

,product_id,product_category_name,product_name_lenght,product_description_lenght,product_photos_qty,product_weight_g,product_length_cm,product_height_cm,product_width_cm
0,1e9e8ef04dbcff4541ed26657ea517e5,perfumaria,40.0,287.0,1.0,225.0,16.0,10.0,14.0
1,3aa071139cb16b67ca9e5dea641aaa2f,artes,44.0,276.0,1.0,1000.0,30.0,18.0,20.0
2,96bd76ec8810374ed1b65e291975717f,esporte_lazer,46.0,250.0,1.0,154.0,18.0,9.0,15.0
3,cef67bcfe19066a932b7673e239eb23d,bebes,27.0,261.0,1.0,371.0,26.0,4.0,26.0
4,9dc1a7de274444849c219cff195d0b71,utilidades_domesticas,37.0,402.0,4.0,625.0,20.0,17.0,13.0

In [122]:
pd.merge(orders, order_items, how='inner', on='order_id')

,order_id,customer_id,order_status,order_purchase_timestamp,order_approved_at,order_delivered_carrier_date,order_delivered_customer_date,order_estimated_delivery_date,order_item_id,product_id,seller_id,shipping_limit_date,price,freight_value
0,e481f51cbdc54678b7cc49136f2d6af7,9ef432eb6251297304e76186b10a928d,delivered,2017-10-02 10:56:33,2017-10-02 11:07:15,2017-10-04 19:55:00,2017-10-10 21:25:13,2017-10-18 00:00:00,1,87285b34884572647811a353c7ac498a,3504c0cb71d7fa48d967e0e4c94d59d9,2017-10-06 11:07:15,29.99,8.72
1,53cdb2fc8bc7dce0b6741e2150273451,b0830fb4747a6c6d20dea0b8c802d7ef,delivered,2018-07-24 20:41:37,2018-07-26 03:24:27,2018-07-26 14:31:00,2018-08-07 15:27:45,2018-08-13 00:00:00,1,595fac2a385ac33a80bd5114aec74eb8,289cdb325fb7e7f891c38608bf9e0962,2018-07-30 03:24:27,118.70,22.76
2,47770eb9100c2d0c44946d9cf07ec65d,41ce2a54c0b03bf3443c3d931a367089,delivered,2018-08-08 08:38:49,2018-08-08 08:55:23,2018-08-08 13:50:00,2018-08-17 18:06:29,2018-09-04 00:00:00,1,aa4383b373c6aca5d8797843e5594415,4869f7a5dfa277a7dca6462dcf3b52b2,2018-08-13 08:55:23,159.90,19.22
3,949d5b44dbf5de918fe9c16f97b45f8a,f88197465ea7920adcdbec7375364d82,delivered,2017-11-18 19:28:06,2017-11-18 19:45:59,2017-11-22 13:39:59,2017-12-02 00:28:42,2017-12-15 00:00:00,1,d0b61bfb1de832b15ba9d266ca96e5b0,66922902710d126a0e7d26b0e3805106,2017-11-23 19:45:59,45.00,27.20
4,ad21c59c0840e6cb83a9ceb5573f8159,8ab97904e6daea8866dbdbc4fb7aad2c,delivered,2018-02-13 21:18:39,2018-02-13 22:20:29,2018-02-14 19:46:34,2018-02-16 18:17:02,2018-02-26 00:00:00,1,65266b2da20d04dbe00c5c2d3bb7859e,2c9e548be18521d1c43cde1c582c6de8,2018-02-19 20:31:37,19.90,8.72
5,a4591c265e18cb1dcee52889e2d8acc3,503740e9ca751ccdda7ba28e9ab8f608,delivered,2017-07-09 21:57:05,2017-07-09 22:10:13,2017-07-11 14:58:04,2017-07-26 10:57:55,2017-08-01 00:00:00,1,060cb19345d90064d1015407193c233d,8581055ce74af1daba164fdbd55a40de,2017-07-13 22:10:13,147.90,27.36
6,136cce7faa42fdb2cefd53fdc79a6098,ed0271e0b7da060a393796590e7b737a,invoiced,2017-04-11 12:22:08,2017-04-13 13:25:17,NaN,NaN,2017-05-09 00:00:00,1,a1804276d9941ac0733cfd409f5206eb,dc8798cbf453b7e0f98745e396cc5616,2017-04-19 13:25:17,49.90,16.05
7,6514b8ad8028c9f2cc2374ded245783f,9bdf08b4b3b52b5526ff42d37d47f222,delivered,2017-05-16 13:10:30,2017-05-16 13:22:11,2017-05-22 10:07:46,2017-05-26 12:55:51,2017-06-07 00:00:00,1,4520766ec412348b8d4caa5e8a18c464,16090f2ca825584b5a147ab24aa30c86,2017-05-22 13:22:11,59.99,15.17
8,76c6e866289321a7c93b82b54852dc33,f54a9f0e6b351c431402b8461ea51999,delivered,2017-01-23 18:29:09,2017-01-25 02:50:47,2017-01-26 14:16:31,2017-02-02 14:08:10,2017-03-06 00:00:00,1,ac1789e492dcd698c5c10b97a671243a,63b9ae557efed31d1f7687917d248a8d,2017-01-27 18:29:09,19.90,16.05
9,e69bfb5eb88e0ed6a785585b27e16dbf,31ad1d1b63eb9962463f764d4e6e0c9d,delivered,2017-07-29 11:55:02,2017-07-29 12:05:32,2017-08-10 19:45:24,2017-08-16 17:14:30,2017-08-23 00:00:00,1,9a78fb9862b10749a117f7fc3c31f051,7c67e1448b00f6e969d365cea6b010ab,2017-08-11 12:05:32,149.99,19.77
10,e6ce16cb79ec1d90b1da9085a6118aeb,494dded5b201313c64ed7f100595b95c,delivered,2017-05-16 19:41:10,2017-05-16 19:50:18,2017-05-18 11:40:40,2017-05-29 11:18:31,2017-06-07 00:00:00,1,08574b074924071f4e201e151b152b4e,001cca7ae9ae17fb1caed9dfb1094831,2017-05-22 19:50:18,99.00,30.53
11,e6ce16cb79ec1d90b1da9085a6118aeb,494dded5b201313c64ed7f100595b95c,delivered,2017-05-16 19:41:10,2017-05-16 19:50:18,2017-05-18 11:40:40,2017-05-29 11:18:31,2017-06-07 00:00:00,2,08574b074924071f4e201e151b152b4e,001cca7ae9ae17fb1caed9dfb1094831,2017-05-22 19:50:18,99.00,30.53
12,34513ce0c4fab462a55830c0989c7edb,7711cf624183d843aafe81855097bc37,delivered,2017-07-13 19:58:11,2017-07-13 20:10:08,2017-07-14 18:43:29,2017-07-19 14:04:48,2017-08-08 00:00:00,1,f7e0fa615b386bc9a8b9eb52bc1fff76,87142160b41353c4e5fca2360caf6f92,2017-07-19 20:10:08,98.00,16.13
13,82566a660a982b15fb86e904c8d32918,d3e3b74c766bc6214e0c830b17ee2341,delivered,2018-06-07 10:06:19,2018-06-09 03:13:12,2018-06-11 13:29:00,2018-06-19 12:05:52,2018-07-18 00:00:00,1,72a97c271b2e429974398f46b93ae530,094ced053e257ae8cae57205592d6712,2018-06-18 03:13:12,31.90,18.23
14,5ff96c15d0b717ac6ad1f3d77225a350,19402a48fe860416adf93348aba37740,delivered,2018-07-25 17:44:10,2018-07-25 17:55:14,2018-07-26 13:16:00,2018-07-30 15:52:25,2018-08-08 00:00:00,1,10adb53d8faa890ca7c2f0cbcb68d777,1900267e848ceeba8fa32d80c1a5f5a8,2018-07-27 17:55:14,19.90,12.80
15,432aaf21d85167c2c86ec9448c4e42cc,3df704f53d3f1d4818840b34ec672a9f,delivered,2018-03-01 14:14:28,2018-03-01 15:10:47,2018-03-02 21:09:20,2018-03-12 23:36:26,2018-03-21 00:00:00,1,72d3bf1d3a790f8874096fcf860e3eff,0bae85eb84b9fb3bd773911e89288d54,2018-03-07 15:10:47,38.25,16.11
16,dcb36b511fcac050b97cd5c05de84dc3,3b6828a50ffe546942b7a473d70ac0fc,delivered,2018-06-07 19:03:12,2018-06-12 23:31:02,2018-06-11 14:54:00,2018-06-21 15:34:32,2018-07-04 00:00:00,1,009c09f439988bc06a93d6b8186dce73,89a51f50b8095ea78d5768f34c13a76f,2018-06-18 18:59:02,132.40,14.05
17,403b97836b0c04a622354cf531062e5f,738b086814c6fcc74b8cc583f8516ee3,delivered,2018-01-02 19:00:43,2018-01-02 19:09:04,2018-01-03 18:19:09,2018-01-20 01:38:59,2018-02-06 00:00:00,1,638bbb2a5e4f360b71f332ddfebfd672,c4af86330efa7a2620772227d2d670c9,2018-01-12 19:09:04,1299.00,77.45
18,116f0b09343b49556bbad5f35bee0cdf,3187789bec990987628d7a9beb4dd6ac,delivered,2017-12-26 23:41:31,2017-12-26 23:50:22,2017-12-28 18:33:05,2018-01-08 22:36:36,2018-01-29 00:00:00,1,a47295965bd091207681b541b26e40a5,ea8482cd71df3c1969d7b9473ff13abc,2018-01-02 23:50:22,27.99,15.10
19,85ce859fd6dc634de8d2f1e290444043,059f7fc5719c7da6cbafe370971a8d70,delivered,2017-11-21 00:03:41,2017-11-21 00:14:22,2017-11-23 21:32:26,2017-11-27 18:28:00,2017-12-11 00:00:00,1,cce679660c66e6fbd5c8091dfd29e9cd,d2374cbcbb3ca4ab1086534108cc3ab7,2017-11-29 00:14:22,17.90,11.85
20,83018ec114eee8641c97e08f7b4e926f,7f8c8b9c2ae27bf3300f670c3d478be8,delivered,2017-10-26 15:54:26,2017-10-26 16:08:14,2017-10-26 21:46:53,2017-11-08 22:22:00,2017-11-23 00:00:00,1,c35498fbb4358837ae16850f50c3fd22,70a12e78e608ac31179aea7f8422044b,2017-11-01 16:07:35,76.00,16.97
21,203096f03d82e0dffbc41ebc2e2bcfb7,d2b091571da224a1b36412c18bc3bbfe,delivered,2017-09-18 14:31:30,2017-09-19 04:04:09,2017-10-06 17:50:03,2017-10-09 22:23:46,2017-09-28 00:00:00,1,5ac9d9e379c606e36a8094a6046f75dc,633ecdf879b94b5337cca303328e4a25,2017-09-25 04:04:09,109.90,8.96
22,f848643eec1d69395095eb3840d2051e,4fa1cd166fa598be6de80fa84eaade43,delivered,2018-03-15 08:52:40,2018-03-15 09:09:31,2018-03-15 19:52:48,2018-03-19 18:08:32,2018-03-29 00:00:00,1,2b4609f8948be18874494203496bc318,cc419e0650a3c5ba77189a1882b7556a,2018-03-23 09:09:31,79.99,8.91
23,2807d0e504d6d4894d41672727bc139f,72ae281627a6102d9b3718528b420f8a,delivered,2018-02-03 20:37:35,2018-02-03 20:50:22,2018-02-05 22:37:28,2018-02-08 16:13:46,2018-02-21 00:00:00,1,6893767814d1ac82a81bcd365e1cc918,8b321bb669392f5163d04c59e235e066,2018-02-08 20:50:22,9.50,7.78
24,95266dbfb7e20354baba07964dac78d5,a166da34890074091a942054b36e4265,delivered,2018-01-08 07:55:29,2018-01-08 08:07:31,2018-01-24 23:16:37,2018-01-26 17:32:38,2018-02-21 00:00:00,1,bb7181410b4e02f93f3697f765db53c7,855668e0971d4dfd7bef1b6a4133b41b,2018-01-26 08:07:31,129.99,57.58
25,f3e7c359154d965827355f39d6b1fdac,62b423aab58096ca514ba6aa06be2f98,delivered,2018-08-09 11:44:40,2018-08-10 03:24:51,2018-08-10 12:29:00,2018-08-13 18:24:27,2018-08-17 00:00:00,1,e99d69efe684efaa643f99805f7c81bc,55c26bcb609f480eb7868594245febb5,2018-08-14 03:24:51,89.90,14.21
26,fbf9ac61453ac646ce8ad9783d7d0af6,3a874b4d4c4b6543206ff5d89287f0c3,delivered,2018-02-20 23:46:53,2018-02-22 02:30:46,2018-02-26 22:25:22,2018-03-21 22:03:54,2018-03-12 00:00:00,1,7b717060aa783eb7f23a747a3a733dd7,c0563dd588b775f2e37747ef6ad6c92c,2018-02-28 02:30:44,109.90,15.53
27,acce194856392f074dbf9dada14d8d82,7e20bf5ca92da68200643bda76c504c6,delivered,2018-06-04 00:00:13,2018-06-05 00:35:10,2018-06-05 13:24:00,2018-06-16 15:20:55,2018-07-18 00:00:00,1,d70f38e7f79c630f8ea00c993897042c,977f9f63dd360c2a32ece2f93ad6d306,2018-06-13 00:35:10,90.90,48.64
28,acce194856392f074dbf9dada14d8d82,7e20bf5ca92da68200643bda76c504c6,delivered,2018-06-04 00:00:13,2018-06-05 00:35:10,2018-06-05 13:24:00,2018-06-16 15:20:55,2018-07-18 00:00:00,2,9451e630d725c4bb7a5a206b48b99486,d673a59aac7a70d8b01e6902bf090a11,2018-06-13 00:35:10,39.50,48.64
29,dd78f560c270f1909639c11b925620ea,8b212b9525f9e74e85e37ed6df37693e,delivered,2018-03-12 01:50:26,2018-03-12 03:28:34,2018-03-12 21:06:37,2018-03-21 14:41:50,2018-03-28 00:00:00,1,00baba5b58e274d0332a0c8a0a66f877,d3f39f05462b79a4562d35893a28f159,2018-03-16 02:30:56,47.90,12.79
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
112620,3cea94817a51f34aa5937784fb4a3219,20b927d23e84dfaa333eb4aea6615084,delivered,2018-04-01 16:13:26,2018-04-01 16:30:16,2018-04-02 18:21:51,2018-04-06 21:32:35,2018-04-19 00:00:00,1,e3dd336775af78a83fc27ed85f0f15da,edb1ef5e36e0c8cd84eb3c9b003e486d,2018-04-05 16:30:16,439.65,20.96
112621,e8fd20068b9f7e6ec07068bb7537f781,609b9fb8cad4fe0c7b376f77c8ab76ad,delivered,2017-08-10 21:21:07,2017-08-10 21:35:26,2017-08-18 16:42:51,2017-08-23 15:36:29,2017-08-31 00:00:00,1,0df37da38a30a713453b03053d60d3f7,218d46b86c1881d022bce9c68a7d4b15,2017-08-17 21:35:26,356.00,18.12
112622,e8fd20068b9f7e6ec07068bb7537f781,609b9fb8cad4fe0c7b376f77c8ab76ad,delivered,2017-08-10 21:21:07,2017-08-10 21:35:26,2017-08-18 16:42:51,2017-08-23 15:36:29,2017-08-31 00:00:00,2,0df37da38a30a713453b03053d60d3f7,218d46b86c1881d022bce9c68a7d4b15,2017-08-17 21:35:26,356.00,18.12
112623,c627fe35fce1a754bc5b812d0b8ff379,42b0671b440d1f2527bddd8b723e0a0c,delivered,2018-06-03 18:44:31,2018-06-03 18:55:15,2018-06-04 13:48:00,2018-06-07 13:22:19,2018-07-11 00:00:00,1,2d4114b81581f8c123e9d78743d9221a,46dc3b2cc0980fb8ec44634e21d2718e,2018-06-11 18:55:15,189.99,16.21
112624,e6cc57f923c4dab2222b8c9aa8742eea,2f4a42f9bb4b9a8cd402fa549df5c7fd,delivered,2018-02-07 12:09:45,2018-02-07 12:31:13,2018-02-21 23:38:05,2018-03-05 18:56:39,2018-05-11 00:00:00,1,7b35ccd93a2184646c03b70326626923,4d6d651bd7684af3fffabd5f08d12e5a,2018-04-17 11:31:13,113.00,15.54
112625,788541a19c0791de0504c5a9cb7e7bd5,a537aaf902d2f436eb7f44817154bb68,delivered,2017-11-30 17:54:28,2017-11-30 18:16:25,2017-12-05 20:58:57,2017-12-13 20:34:50,2017-12-27 00:00:00,1,27d0fc55e3d2fe698088f2603e0a2ab6,02ecc2a19303f05e59ce133fd923fff7,2017-12-06 18:16:25,129.20,18.15
112626,1b4a0e6b19d0034b531655b41ea89623,ce5efd1b1d8a2fa290a871edd5c26cd6,delivered,2017-10-02 08:45:35,2017-10-02 08:56:53,2017-10-03 20:26:19,2017-10-06 16:58:25,2017-10-24 00:00:00,1,9e10ae46a3021a02f1692448ef9fa1db,8b28d096634035667e8263d57ba3368c,2017-10-06 08:56:53,37.90,11.85
112627,f9e3402be5a5ea63344347582ca9f45f,6f2cf56878f7f82151b0ad02590192c0,delivered,2017-06-07 11:02:37,2017-06-08 02:45:24,2017-06-08 14:03:29,2017-06-19 19:19:30,2017-07-05 00:00:00,1,5f21301936c11698db6aee5444190da0,fe2032dab1a61af8794248c8196565c9,2017-06-15 02:45:24,149.90,14.80
112628,6f46d42016226f77893ed3978d6903d0,3803547f820b1e10b7ad9c7985f06753,delivered,2017-07-05 15:55:19,2017-07-05 17:43:48,2017-07-07 19:48:40,2017-07-19 22:10:03,2017-08-14 00:00:00,1,9cbe4a1fd4db99c14512e9b2ff033ec4,d2374cbcbb3ca4ab1086534108cc3ab7,2017-07-25 17:43:48,27.90,15.10
112629,dfc6eb45a2753ed9e6c6ef4987b44503,a046c690e0564ffde0ce611b5eee2c30,delivered,2018-05-25 17:05:17,2018-05-25 17:15:21,2018-05-29 13:31:00,2018-06-04 23:54:32,2018-06-26 00:00:00,1,829002c1d5f40820ebbc6ecd4bcdf3ab,1025f0e2d44d7041d6cf58b6550e0bfa,2018-05-30 17:15:21,150.00,23.63
112630,38e9133ce29f6bbe35aed9c3863dce01,ad312389a098ceff46ce92c4595c06d0,delivered,2017-10-12 20:54:11,2017-10-14 03:28:24,2017-10-17 17:04:42,2017-11-21 17:06:59,2017-10-31 00:00:00,1,014a8a503291921f7b004a5215bb3c36,fa40cc5b934574b62717c68f3d678b6d,2017-10-19 04:28:24,36.90,11.85
112631,6ec4642f9993cc34f826cfb9068e5a2f,f00bb12620b7b232233cace1b229db18,delivered,2017-11-21 20:18:03,2017-11-21 20:28:52,2017-11-27 17:18:52,2017-12-02 16:48:46,2017-12-08 00:00:00,1,9503faef00966962beacdb4916272305,b2ba3715d723d245138f291a6fe42594,2017-11-27 20:28:22,299.90,19.35
112632,d692ef54145c9cb3322ec2e5508aa3f4,82ddfcf9438b0cd1117b55ac33184df8,delivered,2018-03-21 19:47:18,2018-03-21 20:05:26,2018-03-22 21:11:58,2018-04-11 00:48:31,2018-04-09 00:00:00,1,58efb9b638561ce132216a9a612513e2,701938c450705b8ae65fc923b70f35c7,2018-03-27 20:05:26,109.97,36.86
112633,7cc85185736ea7f2d8bc09af7a47cab7,9e870ea67399650e8c3545a25d13e4d0,delivered,2017-05-15 09:46:26,2017-05-15 10:02:45,2017-05-15 14:11:06,2017-05-22 18:05:56,2017-06-07 00:00:00,1,8695c431b31927efef5343e675f279e7,fe2032dab1a61af8794248c8196565c9,2017-05-22 10:02:45,179.90,15.01
112634,19dba6d1e58b04e7fc820558a38ea398,cf97e9cf454480b303de6736ddd15fd6,delivered,2018-05-12 13:42:24,2018-05-12 13:55:17,2018-05-16 08:14:00,2018-05-18 17:18:29,2018-06-04 00:00:00,1,0a57f7d2c983bcf8188589a5fea4a8da,4869f7a5dfa277a7dca6462dcf3b52b2,2018-05-17 13:55:17,96.00,8.79
112635,c22a47117b6a87c967b0c278488110c1,6e153567dc52ea59c0498ef5383e9c7a,delivered,2018-06-22 20:53:29,2018-06-22 21:17:45,2018-06-25 17:50:00,2018-07-03 19:48:54,2018-07-23 00:00:00,1,337a76815f8f765a51535e787101c8fa,391fc6631aebcf3004804e51b40bcf1e,2018-07-02 21:17:45,149.90,16.06
112636,0e4b26f1fb99fc0f0472dd5f403d36d4,2e96fa6d55b9732013caed9866e2552d,delivered,2017-11-05 16:17:53,2017-11-05 16:30:29,2017-11-07 18:35:08,2017-11-08 16:08:56,2017-11-17 00:00:00,1,e71f3cd0a0ef69b7fd173b32322dc6da,520b493b57809f446cb0a233bb3e25c7,2017-11-09 16:30:29,28.00,9.94
112637,c81f74e50f0496fa39716cc77cacd460,7b270ebc87c25c8404348c10ff80a80e,delivered,2018-03-04 22:48:38,2018-03-04 23:09:22,2018-03-05 16:15:04,2018-03-13 18:54:32,2018-03-26 00:00:00,1,cb92637d91f8267856d2143b6fc7bd9e,376a891762bbdecbc02b4b6adec3fdda,2018-03-08 23:09:22,55.00,15.83
112638,b0f4af5c1b06e24fef510703bfe9f0a6,8e1ec396e317ff4c82a03ce16a0c3eb3,delivered,2017-10-27 15:21:00,2017-10-27 15:32:49,2017-10-30 15:44:34,2017-11-10 17:57:22,2017-11-22 00:00:00,1,595fac2a385ac33a80bd5114aec74eb8,058fd0aa2bfdb2274e05e1ae971dabb6,2017-11-03 15:30:22,142.50,21.80
112639,cfa78b997e329a5295b4ee6972c02979,a2f7428f0cafbc8e59f20e1444b67315,delivered,2017-12-20 09:52:41,2017-12-20 10:09:52,2017-12-20 20:25:25,2018-01-26 15:45:14,2018-01-18 00:00:00,1,3d2c44374ee42b3003a470f3e937a2ea,ce248b21cb2adc36282ede306b7660e5,2017-12-27 10:09:52,55.90,15.14
112640,9115830be804184b91f5c00f6f49f92d,da2124f134f5dfbce9d06f29bdb6c308,delivered,2017-10-04 19:57:37,2017-10-04 20:07:14,2017-10-05 16:52:52,2017-10-20 20:25:45,2017-11-07 00:00:00,1,c982dbea53b864f4d27c1d36f14b6053,1caf283236cd69af44cbc09a0a1e7d32,2017-10-10 20:07:14,42.11,0.80
112641,9115830be804184b91f5c00f6f49f92d,da2124f134f5dfbce9d06f29bdb6c308,delivered,2017-10-04 19:57:37,2017-10-04 20:07:14,2017-10-05 16:52:52,2017-10-20 20:25:45,2017-11-07 00:00:00,2,49d2e2460386273b195e7e59b43587c3,1caf283236cd69af44cbc09a0a1e7d32,2017-10-10 20:07:14,26.90,36.98
112642,aa04ef5214580b06b10e2a378300db44,f01a6bfcc730456317e4081fe0c9940e,delivered,2017-01-27 00:30:03,2017-01-27 01:05:25,2017-01-30 11:40:16,2017-02-07 13:15:25,2017-03-17 00:00:00,1,9fc063fd34fed29ccc57b7f8e8d03388,ccc4bbb5f32a6ab2b7066a4130f114e3,2017-02-03 00:30:03,370.00,19.43
112643,880675dff2150932f1601e1c07eadeeb,47cd45a6ac7b9fb16537df2ccffeb5ac,delivered,2017-02-23 09:05:12,2017-02-23 09:15:11,2017-03-01 10:22:52,2017-03-06 11:08:08,2017-03-22 00:00:00,1,ea73128566d1b082e5101ce46f8107c7,391fc6631aebcf3004804e51b40bcf1e,2017-02-27 09:05:12,139.90,16.09
112644,9c5dedf39a927c1b2549525ed64a053c,39bd1228ee8140590ac3aca26f2dfe00,delivered,2017-03-09 09:54:05,2017-03-09 09:54:05,2017-03-10 11:18:03,2017-03-17 15:08:01,2017-03-28 00:00:00,1,ac35486adb7b02598c182c2ff2e05254,e24fc9fcd865784fb25705606fe3dfe7,2017-03-15 09:54:05,72.00,13.08
112645,63943bddc261676b46f01ca7ac2f7bd8,1fca14ff2861355f6e5f14306ff977a7,delivered,2018-02-06 12:58:58,2018-02-06 13:10:37,2018-02-07 23:22:42,2018-02-28 17:37:56,2018-03-02 00:00:00,1,f1d4ce8c6dd66c47bbaa8c6781c2a923,1f9ab4708f3056ede07124aad39a2554,2018-02-12 13:10:37,174.90,20.10
112646,83c1379a015df1e13d02aae0204711ab,1aa71eb042121263aafbe80c1b562c9c,delivered,2017-08-27 14:46:43,2017-08-27 15:04:16,2017-08-28 20:52:26,2017-09-21 11:24:17,2017-09-27 00:00:00,1,b80910977a37536adeddd63663f916ad,d50d79cb34e38265a8649c383dcffd48,2017-09-05 15:04:16,205.99,65.02
112647,11c177c8e97725db2631073c19f07b62,b331b74b18dc79bcdf6532d51e1637c1,delivered,2018-01-08 21:28:27,2018-01-08 21:36:21,2018-01-12 15:35:03,2018-01-25 23:32:54,2018-02-15 00:00:00,1,d1c427060a0f73f6b889a5c7c61f2ac4,a1043bafd471dff536d0c462352beb48,2018-01-12 21:36:21,179.99,40.59
112648,11c177c8e97725db2631073c19f07b62,b331b74b18dc79bcdf6532d51e1637c1,delivered,2018-01-08 21:28:27,2018-01-08 21:36:21,2018-01-12 15:35:03,2018-01-25 23:32:54,2018-02-15 00:00:00,2,d1c427060a0f73f6b889a5c7c61f2ac4,a1043bafd471dff536d0c462352beb48,2018-01-12 21:36:21,179.99,40.59
112649,66dea50a8b16d9b4dee7af250b4be1a5,edb027a75a1449115f6b43211ae02a24,delivered,2018-03-08 20:57:30,2018-03-09 11:20:28,2018-03-09 22:11:59,2018-03-16 13:08:30,2018-04-03 00:00:00,1,006619bbed68b000c8ba3f8725d5409e,ececbfcff9804a2d6b40f589df8eef2b,2018-03-15 10:55:42,68.50,18.36

In [125]:
orders_combined = pd.merge(pd.merge(pd.merge(pd.merge(pd.merge(orders, order_items, how='inner', on='order_id'), order_payments, how='inner', on='order_id'), products, how='inner', on='product_id'), customers, how='inner', on='customer_id'), sellers, how='inner', on='seller_id')

In [126]:
orders_combined.columns

Index(['order_id', 'customer_id', 'order_status', 'order_purchase_timestamp',
       'order_approved_at', 'order_delivered_carrier_date',
       'order_delivered_customer_date', 'order_estimated_delivery_date',
       'order_item_id', 'product_id', 'seller_id', 'shipping_limit_date',
       'price', 'freight_value', 'payment_sequential', 'payment_type',
       'payment_installments', 'payment_value', 'product_category_name',
       'product_name_lenght', 'product_description_lenght',
       'product_photos_qty', 'product_weight_g', 'product_length_cm',
       'product_height_cm', 'product_width_cm', 'customer_unique_id',
       'customer_zip_code_prefix', 'customer_city', 'customer_state',
       'seller_zip_code_prefix', 'seller_city', 'seller_state'],
      dtype='object')

In [120]:
pandas_profiling.ProfileReport(orders_combined).to_file(outputfile="orders_combined_before.html")

# Product table cleaning

In [75]:
#description length and name length doesn't make sense, possibly masked data
products.drop("product_description_lenght", axis=1, inplace=True)
products.drop("product_name_lenght", axis=1, inplace=True)

In [76]:
#product_category_name, product_description_lenght, product_name_lenght, product_photos_qty; all have missing values for exactly 610 same rows
cat_name_na = products["product_category_name"].isna()
photo_qty_na = products["product_photos_qty"].isna()
na_index = products[(cat_name_na) & (photo_qty_na)].index
print(na_index) # outputs 610
previous_rows = products.shape[0]
products.drop(index=na_index, axis=0, inplace=True)
print("Previous rows: {}, Current rows: {}, Diff: {}".format(str(previous_rows), str(products.shape[0]), str(previous_rows - products.shape[0])))

Int64Index([  105,   128,   145,   154,   197,   244,   294,   299,   347,
              428,
            ...
            32446, 32458, 32460, 32476, 32487, 32515, 32589, 32616, 32772,
            32852],
           dtype='int64', length=610)
Previous rows: 32951, Current rows: 32341, Diff: 610

* Replace brazillian category names to english and get rid of the translation df alltogether.
* There are 71 unique category name translations, but product has 73 unique category

In [88]:
products.head()[products['product_category_name'].head().isin(['artes','bebes'])]

,product_id,product_category_name,product_photos_qty,product_weight_g,product_length_cm,product_height_cm,product_width_cm
1,3aa071139cb16b67ca9e5dea641aaa2f,artes,1.0,1000.0,30.0,18.0,20.0
3,cef67bcfe19066a932b7673e239eb23d,bebes,1.0,371.0,26.0,4.0,26.0

In [98]:
# Find out the 2 category names which are not present in the category translation df
print(cat_translate['product_category_name'].nunique())
print(products['product_category_name'].nunique())

valid_cat_trans = set(cat_translate['product_category_name'].unique())
all_pdt_cats = set(products['product_category_name'].unique())
invalid_cats = list(all_pdt_cats - valid_cat_trans)
print(invalid_cats)
invalid_cats_pdt = products['product_category_name'].isin(invalid_cats)
previous_rows = products.shape[0]
products = products[~(invalid_cats_pdt)]
print("Previous rows: {}, Current rows: {}, Diff: {}".format(str(previous_rows), str(products.shape[0]), str(previous_rows - products.shape[0])))

71
73
['portateis_cozinha_e_preparadores_de_alimentos', 'pc_gamer']
Previous rows: 32341, Current rows: 32328, Diff: 13

In [99]:
cat_translate.head()

    product_category_name product_category_name_english
0            beleza_saude                 health_beauty
1  informatica_acessorios         computers_accessories
2              automotivo                          auto
3         cama_mesa_banho                bed_bath_table
4        moveis_decoracao               furniture_decor

In [104]:
products = pd.merge(products,cat_translate, how='inner', on='product_category_name').drop('product_category_name', axis=1)

In [105]:
products.head()

,product_id,product_photos_qty,product_weight_g,product_length_cm,product_height_cm,product_width_cm,product_category_name_english
0,1e9e8ef04dbcff4541ed26657ea517e5,1.0,225.0,16.0,10.0,14.0,perfumery
1,6a2fb4dd53d2cdb88e0432f1284a004c,2.0,400.0,27.0,5.0,20.0,perfumery
2,0d009643171aee696f4733340bc2fdd0,1.0,422.0,21.0,16.0,18.0,perfumery
3,b1eae565a61935e0011ee7682fef9dc9,2.0,267.0,17.0,13.0,17.0,perfumery
4,8da90b37f0fb171b4877c124f965b1f6,3.0,377.0,18.0,13.0,15.0,perfumery

In [107]:
print(products.shape[0])
print(products.product_id.nunique())

32328
32328

In [109]:
products.describe()

,product_photos_qty,product_weight_g,product_length_cm,product_height_cm,product_width_cm
count,32328.000000,32327.000000,32327.000000,32327.000000,32327.000000
mean,2.188815,2276.960807,30.856498,16.955950,23.208464
std,1.736746,4279.734063,16.958460,13.637246,12.080665
min,1.000000,0.000000,7.000000,2.000000,6.000000
25%,1.000000,300.000000,18.000000,8.000000,15.000000
50%,1.000000,700.000000,25.000000,13.000000,20.000000
75%,3.000000,1900.000000,38.000000,20.500000,30.000000
max,20.000000,40425.000000,105.000000,105.000000,118.000000

In [111]:
products['product_weight_g'].plot.hist()

In [106]:
pandas_profiling.ProfileReport(products).to_file(outputfile="products_before.html")

In [129]:
order_items.head()

,order_id,order_item_id,product_id,seller_id,shipping_limit_date,price,freight_value
0,00010242fe8c5a6d1ba2dd792cb16214,1,4244733e06e7ecb4970a6e2683c13e61,48436dade18ac8b2bce089ec2a041202,2017-09-19 09:45:35,58.90,13.29
1,00018f77f2f0320c557190d7a144bdd3,1,e5f2d52b802189ee658865ca93d83a8f,dd7ddc04e1b6c2c614352b383efe2d36,2017-05-03 11:05:13,239.90,19.93
2,000229ec398224ef6ca0657da4fc703e,1,c777355d18b72b67abbeef9df44fd0fd,5b51032eddd242adc84c38acab88f23d,2018-01-18 14:48:30,199.00,17.87
3,00024acbcdf0a6daa1e931b038114c75,1,7634da152a4610f1595efa32f14722fc,9d7a1d34a5052409006425275ba1c2b4,2018-08-15 10:10:18,12.99,12.79
4,00042b26cf59d7ce69dfabb4e55b4fd9,1,ac6c3623068f30de03045865e4e10089,df560393f3a51e74553ab94004ba5c87,2017-02-13 13:57:51,199.90,18.14